[build]
  command = "git config --global url.'https://github.com/'.insteadOf 'git@github.com:' && git config --global url.'https://github.com/'.insteadOf 'ssh://git@github.com/' && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "1.22.22"

# Enable Next.js plugin for server-side functionality and API routes
[[plugins]]
  package = "@netlify/plugin-nextjs"